import express from 'express';
const app = express();
import routerGuest from './routerGuest.js'
import routerUser from './routerUser.js'

import dotenv from 'dotenv'
dotenv.config()

import jwt from 'jsonwebtoken'

import cors from 'cors'

const { sign } = jwt

import mysql from 'mysql2';

import mysql_getUserPasswd from './sql_modules/sql_getUserPasswd.js';
import mysql_getUsers from './sql_modules/sql_getUsers.js';
import mysql_addUser from './sql_modules/sql_addUser.js';

app.use(express.json());

app.use(cors());

var con = mysql.createConnection({
    host: "localhost",
    user: "root",
    password: "pass4root",
    database: "cse316_assignment3"
});

// Signup, Login and Logout

// Sign in
// POST call because we need to get a token.
app.post('/login', async (req,res) => {
    // TODO - How can I use just 1 connection for all 3 routers?
    // This one, routerGuest and routerUser
    // Username and Password are provided in login screen (see Part6.jsx in src/)
    // const userEmail = req.body.userEmail
    // Password should be hashed in the client, not the server, as we cannot use HTTPS.
    // const userPasswd = req.body.userPasswd
    // const userName = "'" + req.body.userName + "'";
    const hashPasswd = "'" + req.body.userPasswd + "'";
    let newUser;

    // Retrieve user from userEmail and userPasswd combination
    // Or should I do this in the front-end?

    try{
        newUser = await mysql_getUserPasswd(con, userName, hashPasswd);
        if(!newUser){
            res.status(404).send('Wrong email or wrong password');
            return;
        }
        else{
            console.log(newUser);
        }
    }
    catch (err) {
      res.status(500).send("Error: "+err);
      return;
    }

    // Possibility of hash collision by any chance?
    // IF LOGIN SUCCESSFUL, generate access token
    const accessToken = generateAccessToken(newUser)
    // Send an Access Token and User as JSON pair
    console.log({"accessToken":accessToken, "user":newUser});
    res.send({"accessToken":accessToken,"user":newUser});
})

// POST - user
// Add a user for sign up
app.post('/signup', async (req,res)=>{
    try{
        // Instantiate new user object to be pushed
        let newUser = {
            // For some reason, when forms are submitted this way, the brackets come off
            // "'" was added for strings and the date type for this reason
            userName: "'"+req.body.userName+"'",
            userPasswd: "'"+req.body.userPasswd+"'",
            userEmail: "'"+req.body.userEmail+"'"
        }
        console.log(newUser);
        // Check if username+password hash combo exists
        // Check if email already exists in database
        const check = await mysql_getUsers(con);
        console.log(check);
        // HINT: Grab the response with (res.response.data)
        for(const user of check){
            if(user.userEmail === req.body.userEmail){
                res.status(500).send("Email already exists");
                return;
            }
            // Any chance of hash collision?
            else if(user.userPasswd === req.body.userPasswd){
                res.status(500).send("Username and Password combination exists");
                return;
            }
        }
        // Push new user to users (in database) to finish
        // Cookie is generated by the front end, in case Jenny wondered
        // Either that, or maybe I need help here from Jenny
        const result = await mysql_addUser(con, newUser);
        res.send(result);
    }
    catch (err) {
        res.status(500).send("Error: "+err);
    }
})

// Sign out
// Mostly done by cookies - maybe I should ask for Jenny for this?
app.delete('/logout', (req,res) => {
    res.sendStatus(204);
})

// Generate Access Token
function generateAccessToken(user) {
    console.log(`Access token generated for ${user.userName}`);
    return sign(user, process.env.ACCESS_TOKEN_SECRET, {expiresIn: '1d'})
}

// Authenticate Token
function authenticateToken(req, res, next) {
    // Bearer TOKEN
    const authHeader = req.headers['authorization']
    // IF we have authHeader, return undefined or actual token
    const token = authHeader && authHeader.split(" ")[1]

    if (token == null) {
        return res.sendStatus(401)
    }

    jwt.verify(token, process.env.ACCESS_TOKEN_SECRET, (err, user) => {
        if (err) {
            return res.sendStatus(403)
        }
        req.user = user
        next()
    })
}

// Should there be a single router, or can multiple routers coexist?
// Guests can see (often corresponds to GET operations)
app.use('/api', routerGuest);
// Authenticated users can add/modify (often corresponds to POST and PUT operations)
app.use('/api/auth', authenticateToken, routerUser);

let port = process.env.PORT || 3000;
app.listen(port, () => {console.log(`listening on port ${port}...`)})